Gh policies
scribe-public/sample-policies pull request #39
Opened 2024-06-17 13:50 UTC by gabrielscribe

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/create-private-repos.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false # Enter true or false
  
```

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/create-repos.rego
> +
```suggestion
```

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependabot-alerts.rego
> +
```suggestion
```

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependabot-alerts.rego
> +			"id": organization.name,
There's no point in having the same value twice

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependabot-alerts.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false # Enter true or false
  
```

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependabot-security-updates.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false # Enter true or false
  
```

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependabot-security-updates.rego
> +
```suggestion
```

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependency-graph.rego
> +
```suggestion
```

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependency-graph.rego
> +			"id": organization.name,
same

2024-06-24 10:35 UTC, cppvik commented on v1/github/org/dependency-graph.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false # Enter true or false
  
```

... and so on

2024-06-27 06:50 UTC, cppvik commented on v1/github/org/create-private-repos.yaml
> +  desired_value: false # Enter true or false
This should be applied to all the files with "no newline at the end of the file"

2024-06-27 07:15 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-dependabot_security_updates.rego
> +			"dependabot_security_updates_enabled_for_new_repositories": dependabot_security_updates,
```suggestion
			"security_updates_enabled": dependabot_security_updates,
```

2024-06-27 07:16 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-dependabot_security_updates.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.dependabot_security_updates.status,
```

2024-06-27 07:17 UTC, cppvik commented on v1/github/org/dependabot-security-updates-sa.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.dependabot_security_updates.status,
```

2024-06-27 07:19 UTC, cppvik commented on v1/github/org/secret-scanning-sa.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning.status,
```

2024-06-27 07:20 UTC, cppvik commented on v1/github/org/validity-checks-sa.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_validity_checks.status,
```

2024-06-27 07:21 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-secret_scanning.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning.status,
```

2024-06-27 07:21 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-secret_scanning_push_protection.rego
> +			"secret_scanning_push_protection_enabled_for_new_repositories": secret_scanning_push_protection,
```suggestion
			"push_protection_enabled": secret_scanning_push_protection,
```

2024-06-27 07:21 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-secret_scanning_push_protection.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_push_protection.status,
```

2024-06-27 07:22 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-secret_scanning_push_protection.rego
> +check_secret_scanning_push_protection_enabled_for_new_repositories(repository, secret_scanning_push_protection) {
Please try to avoid such long function names, it's hard to read and doesn't match the codestyle of the repo

2024-06-27 07:23 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-secret_scanning_validity_checks.rego
> +			"secret_scanning_validity_checks_enabled": secret_scanning_validity_checks,
```suggestion
			"validity_checks_enabled": secret_scanning_validity_checks,
```

2024-06-27 07:23 UTC, cppvik commented on v1/github/organization attestation/test-security-and-analysis-secret_scanning_validity_checks.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_validity_checks.status,
```

2024-06-27 07:23 UTC, cppvik commented on v1/github/repository attestation/fail-on-branch-protected.rego
> +			"desired_protected": desired_protected,
```suggestion
```

2024-06-27 07:24 UTC, cppvik commented on v1/github/repository attestation/fail-on-branch-verified.rego
> +			}
```suggestion
```

2024-06-27 07:24 UTC, cppvik commented on v1/github/repository attestation/fail-on-repo-visibility.rego
> +			"allowed_repo_names": allowed_repo_names,
```suggestion
```

2024-06-27 07:24 UTC, cppvik commented on v1/github/repository attestation/fail-on-secrets-older-than-k-months.rego
> +			"months": months,
```suggestion
			"created_at": ts,
```

2024-06-27 07:24 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-dependabot_security_updates.rego
> +			"dependabot_security_updates_enabled_for_new_repositories": dependabot_security_updates,
```suggestion
			"security_updates_enabled": dependabot_security_updates,
```

2024-06-27 07:25 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-dependabot_security_updates.rego
> +				}
```suggestion
			"dependabot_security_updates_status":  {				repository.result_object.security_and_analysis.dependabot_security_updates.status,
```

2024-06-27 07:25 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-secret_scanning.rego
> +			"secret_scanning_enabled_for_new_repositories": secret_scanning,
```suggestion
			"secret_scanning_enabled": secret_scanning,
```

2024-06-27 07:25 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-secret_scanning.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning.status,
```

2024-06-27 07:26 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-secret_scanning_push_protection.rego
> +			"secret_scanning_push_protection_enabled_for_new_repositories": secret_scanning_push_protection,
```suggestion
			"push_protection_enabled": secret_scanning_push_protection,
```

2024-06-27 07:26 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-secret_scanning_push_protection.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_push_protection.status,
```

2024-06-27 07:26 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-secret_scanning_validity_checks.rego
> +			"secret_scanning_validity_checks_enabled": secret_scanning_validity_checks,
```suggestion
			"validity_checks_enabled": secret_scanning_validity_checks,
```

2024-06-27 07:26 UTC, cppvik commented on v1/github/repository attestation/test-security-and-analysis-secret_scanning_validity_checks.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_validity_checks.status,
```

2024-06-27 07:27 UTC, cppvik commented on v1/github/repository/branch-protection.rego
> +			"desired_protected": desired_protected,
```suggestion
```

2024-06-27 07:27 UTC, cppvik commented on v1/github/repository/branch-verification.rego
> +			}
```suggestion
			"head_commit_verification_status":  verified
```

2024-06-27 07:27 UTC, cppvik commented on v1/github/repository/dependabot.rego
> +			"dependabot_security_updates_enabled_for_new_repositories": dependabot_security_updates,
```suggestion
			"security_updates_enabled": dependabot_security_updates,
```

2024-06-27 07:29 UTC, cppvik commented on v1/github/repository/dependabot.rego
> +			}
```suggestion
			"dependabot_security_updates_status":
repository.result_object.security_and_analysis.dependabot_security_updates.status,
```

2024-06-27 07:29 UTC, cppvik commented on v1/github/repository/old-secrets.rego
> +			"months": months,
```suggestion
			"k": k,
			"created_at": ts,
			"months": months,
```
```suggestion
			"created_at": ts,
```

2024-06-27 07:29 UTC, cppvik commented on v1/github/repository/push-protection.rego
> +			"secret_scanning_push_protection_enabled_for_new_repositories": secret_scanning_push_protection,
```suggestion
			"push_protection_enabled": secret_scanning_push_protection,
```

2024-06-27 07:29 UTC, cppvik commented on v1/github/repository/push-protection.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_push_protection.status,
```

2024-06-27 07:30 UTC, cppvik commented on v1/github/repository/secret-scanning.rego
> +			"secret_scanning_enabled_for_new_repositories": secret_scanning,
```suggestion
			"secret_scanning_enabled": secret_scanning,
```

2024-06-27 07:30 UTC, cppvik commented on v1/github/repository/secret-scanning.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning.status,
```

2024-06-27 07:31 UTC, cppvik commented on v1/github/repository/validity-checks.rego
> +			"secret_scanning_validity_checks_enabled": secret_scanning_validity_checks,
```suggestion
			"validity_checks_enabled": secret_scanning_validity_checks,
```

2024-06-27 07:31 UTC, cppvik commented on v1/github/repository/validity-checks.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_validity_checks.status,
```

2024-06-27 07:31 UTC, cppvik commented on v1/github/repository/visibility.rego
> +			"allowed_repo_names": allowed_repo_names,
```suggestion
```

2024-06-27 07:32 UTC, cppvik commented on v1/github/org/push-protection-sa.rego
> +			}
```suggestion
			"security_and_analysis_status": repository.result_object.security_and_analysis.secret_scanning_push_protection.status,
```

2024-07-14 07:35 UTC, gabrielscribe commented on v1/github/organization attestation/fail-on-secrets-older-than-k-months.rego
> +			"k": k,
k is the number of months allowed

2024-07-14 12:07 UTC, cppvik requested changes

2024-07-14 12:07 UTC, cppvik commented on v1/github/repository/old-secrets.yaml
> +  k: 12 # Enter an numerical value
What is `k`? Please reanem

2024-07-14 12:07 UTC, cppvik commented on v1/github/repository/visibility.yaml
> +    - "scribe-security/.*"
```suggestion
  allowed_repo_names: []
```

2024-07-14 12:19 UTC, cppvik requested changes

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/2fa.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/advanced-security.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/create-private-repos.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/dependabot-alerts.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/dependabot-security-updates.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/dependency-graph.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/pp-custom-link.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/push-protection.yaml
> +  desired_value: true # Enter true or false
```suggestion
  desired_value: true
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/secret-scanning.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/validity-checks.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/web-commit-signoff.yaml
> +  desired_value: false # Enter true or false
```suggestion
  desired_value: false
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/org/repo-visibility.yaml
> +    -
```suggestion
  allowed_repo_names: []
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/repository/branch-protection.yaml
> +  desired_protected: true # Will fail for branches that do not share the same value as this one.
```suggestion
  desired_protected: true
```

2024-07-14 12:19 UTC, cppvik commented on v1/github/repository/branch-verification.yaml
> +  desired_verified: false # Will fail for branches that do not share the same value as this one.
```suggestion
  desired_verified: false
```

2024-07-15 12:23 UTC, merged